---
# tasks file for system-demo

- name: Get config for EOS devices
  eos_facts:
   gather_subset: all

- name: configure dns-domain
  eos_config:
   lines: dns domain {{dnsdomain}}

- name: display config   
  debug:
   msg: "The hostname is {{ ansible_net_fqdn }} and the OS is {{ ansible_net_version }} and SN is {{ ansible_net_serialnum }}"

- name: Write facts to disk using a template
  copy:
    content: |
     #jinja2: lstrip_blocks: True
     EOS device info:
      {% for host in groups['cre'] %}
      Hostname: {{ hostvars[host].ansible_net_hostname }}
      Version: {{ hostvars[host].ansible_net_version }}
      Model: {{ hostvars[host].ansible_net_model }}
      Serial: {{ hostvars[host].ansible_net_serialnum }}
      {% endfor %}
    dest: /tmp/switch-facts
  run_once: yes
###
# Get running configuration
#

- name: Backup switch (eos)
  eos_config:
    backup: yes
  register: backup_eos_location
  when: ansible_network_os == 'eos'

- name: Create backup dir
  file:
    path: "/tmp/backups/{{ inventory_hostname }}"
    state: directory
    recurse: yes

- name: Copy backup files into /tmp/backups/ (eos)
  copy:
    src: "{{ backup_eos_location.backup_path }}"
    dest: "/tmp/backups/{{ inventory_hostname }}/{{ inventory_hostname }}.bck"
  when: ansible_network_os == 'eos'
